# name 可以自定义
name: Deploy GitHub Pages

# 触发条件：在 push 到 main/master 分支后，新的 Github 项目 应该都是 main，而之前的项目一般都是 master
on:
  push:
    branches:
      - master # 注意，这里是master，一定要看好是master还是main，否则不会触发事件！！！

# 任务
name: Deploy GitHub Pages

# 触发条件：在 push 到 main/master 分支后触发
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 步骤1：拉取代码
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # 步骤2：设置Node.js 16.x
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # 步骤3：安装依赖并构建项目
      - name: Install and Build
        run: |
          npm install
          npm run build:win # 确保这个脚本在package.json中定义，并且适用于Linux环境

      # 步骤4：部署到 GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist
          CLEAN: true # 清理目标文件夹
          SINGLE_COMMIT: true # 部署单个提交 

